# Site settings
title: "Agile Market"
email: "info@agilemarket.co.uk"  
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.agilemarket.co.uk" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
